tap "caskroom/cask"
tap "cj-bc/cj-bc"
tap "cloudfoundry/tap"
tap "fumiyas/echo-sd"
tap "go-delve/delve"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/services"
tap "jlhonora/lsusb"
tap "railwaycat/emacsmacport"
tap "sanemat/font"
brew "libyaml"
brew "readline", link: true
brew "xz"
brew "ansible"
brew "arp-scan"
brew "autoconf"
brew "autojump"
brew "automake"
brew "gettext"
brew "axel"
brew "bash"
brew "bat"
brew "gcc"
brew "binwalk"
brew "boost"
brew "ghc"
brew "cabal-install"
brew "libpng"
brew "glib"
brew "pixman"
brew "cmake"
brew "openblas"
brew "chromedriver"
brew "cliclick"
brew "composer"
brew "coreutils"
brew "cowsay"
brew "cpanminus"
brew "cscope"
brew "ctags"
brew "curl"
brew "direnv"
brew "docker", link: false
brew "e2fsprogs"
brew "envchain"
brew "jpeg"
brew "libtiff"
brew "erlang"
brew "exiftool"
brew "fd"
brew "libevent"
brew "gnutls"
brew "tesseract"
brew "ffmpeg"
brew "figlet"
brew "flow", link: false
brew "libtool"
brew "pango"
brew "fontforge"
brew "gcc@4.9"
brew "gcc@5"
brew "gd"
brew "gdb"
brew "ghostscript"
brew "gibo"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "glslang"
brew "go"
brew "pkg-config"
brew "gobject-introspection"
brew "graphviz"
brew "guetzli"
brew "hashpump"
brew "haskell-stack"
brew "hub"
brew "ilmbase"
brew "openexr"
brew "imagemagick"
brew "imagemagick@6"
brew "imagesnap"
brew "iproute2mac"
brew "jpeg-turbo"
brew "jpegoptim"
brew "oniguruma"
brew "jq"
brew "kotlin"
brew "leiningen"
brew "lha"
brew "libidn"
brew "libwebsockets"
brew "libxmlsec1"
brew "lua"
brew "lv"
brew "lynx"
brew "ruby"
brew "macvim", link: false
brew "mas"
brew "mercurial"
brew "minicom"
brew "mosquitto"
brew "mysql", link: false
brew "nginx"
brew "nkf"
brew "nmap"
brew "node", link: false
brew "numpy"
brew "oath-toolkit"
brew "opencv"
brew "packer"
brew "pacvim"
brew "peco"
brew "pipenv"
brew "pngcheck"
brew "pngquant"
brew "portaudio"
brew "postgresql", restart_service: true
brew "postgresql@10"
brew "protobuf"
brew "pup"
brew "pwgen"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis"
brew "rlwrap"
brew "rmtrash"
brew "rtv"
brew "shadowsocks-libev"
brew "sl"
brew "socat"
brew "source-highlight"
brew "starship"
brew "swiftlint"
brew "telnet"
brew "terminal-notifier"
brew "tig"
brew "tmux"
brew "tofrodos"
brew "tree"
brew "vim"
brew "w3m"
brew "watch"
brew "watchman"
brew "wget"
brew "wine"
brew "yarn", link: false
brew "zlib"
brew "zplug", link: false
brew "zsh"
brew "cloudfoundry/tap/cf-cli"
brew "fumiyas/echo-sd/echo-sd"
brew "heroku/brew/heroku"
brew "jlhonora/lsusb/lsusb"
brew "sanemat/font/ricty"
cask "1password"
cask "alfred"
cask "android-studio"
cask "appcode"
cask "atom"
cask "balsamiq-mockups"
cask "basictex"
cask "bathyscaphe"
cask "bettertouchtool"
cask "chromium"
cask "dash"
cask "dbeaver-community"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "franz"
cask "gimp"
cask "google-chrome"
cask "graphiql"
cask "hyper"
cask "hyperswitch"
cask "insomnia"
cask "intellij-idea"
cask "iterm2"
cask "java"
cask "kap"
cask "keyboard-cleaner"
cask "keycastr"
cask "kindle"
cask "minecraft"
cask "pycharm"
cask "rubymine"
cask "sketch"
cask "skim"
cask "skitch"
cask "skype"
cask "slack"
cask "steam"
cask "teamsql"
cask "vagrant"
cask "visual-studio-code"
cask "webstorm"
cask "xquartz"
mas "Bandwidth+", id: 490461369
mas "Cyberduck", id: 409222199
mas "Display Menu", id: 549083868
mas "Evernote", id: 406056744
mas "GarageBand", id: 682658836
mas "GrandPerspective", id: 1111570163
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "ScanSnap Cloud", id: 1035516352
mas "Shazam", id: 897118787
mas "Sim Daltonism", id: 693112260
mas "TEPRA SMA3", id: 704088911
mas "The Unarchiver", id: 425424353
mas "Tomato One", id: 907364780
mas "Xcode", id: 497799835
