tap "cj-bc/cj-bc"
tap "cloudfoundry/tap"
tap "fumiyas/echo-sd"
tap "go-delve/delve"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/services"
tap "jlhonora/lsusb"
tap "railwaycat/emacsmacport"
tap "sanemat/font"
brew "libyaml"
brew "openssl"
brew "readline", link: true
brew "xz"
brew "ansible"
brew "arp-scan"
brew "autoconf"
brew "autojump"
brew "automake"
brew "gettext"
brew "axel"
brew "bash"
brew "bat"
brew "gcc"
brew "binwalk"
brew "boost"
brew "libpng"
brew "pixman"
brew "chromedriver"
brew "cmake"
brew "composer"
brew "coreutils"
brew "cpanminus"
brew "cscope"
brew "ctags"
brew "curl"
brew "direnv"
brew "docker"
brew "e2fsprogs"
brew "envchain"
brew "jpeg"
brew "libtiff"
brew "erlang"
brew "exiftool"
brew "fd"
brew "ffmpeg"
brew "figlet"
brew "flow", link: false
brew "libtool"
brew "pango"
brew "fontforge"
brew "gcc@4.9"
brew "gcc@5"
brew "gd"
brew "gdb"
brew "ghostscript"
brew "gibo"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "glslang"
brew "libevent"
brew "go"
brew "pkg-config"
brew "graphviz"
brew "guetzli"
brew "hashpump"
brew "haskell-stack"
brew "hub"
brew "ilmbase"
brew "imagemagick"
brew "imagemagick@6"
brew "imagesnap"
brew "iproute2mac"
brew "jpeg-turbo"
brew "jpegoptim"
brew "oniguruma"
brew "jq"
brew "kotlin"
brew "lha"
brew "libidn"
brew "lua"
brew "lv"
brew "lynx"
brew "macvim", args: ["with-lua"]
brew "mas"
brew "mercurial"
brew "minicom"
brew "mosquitto"
brew "mysql"
brew "nginx"
brew "nkf"
brew "nmap"
brew "oath-toolkit"
brew "openexr"
brew "opencv"
brew "packer"
brew "pacvim"
brew "peco"
brew "pngcheck"
brew "portaudio"
brew "postgresql", restart_service: true
brew "protobuf"
brew "pup"
brew "pwgen"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis"
brew "rlwrap"
brew "rmtrash"
brew "rtv"
brew "shadowsocks-libev"
brew "sl"
brew "socat"
brew "source-highlight"
brew "swiftlint"
brew "telnet"
brew "terminal-notifier"
brew "tesseract"
brew "tig"
brew "tmux"
brew "tofrodos"
brew "tree"
brew "vim", args: ["with-lua"]
brew "w3m"
brew "watch"
brew "watchman"
brew "wget"
brew "yarn", link: false
brew "zlib"
brew "zplug", link: false
brew "zsh"
brew "cloudfoundry/tap/cf-cli"
brew "fumiyas/echo-sd/echo-sd"
brew "heroku/brew/heroku"
brew "jlhonora/lsusb/lsusb"
brew "sanemat/font/ricty"
cask "1password"
cask "alfred"
cask "android-studio"
cask "appcode"
cask "atom"
cask "balsamiq-mockups"
cask "basictex"
cask "bathyscaphe"
cask "bettertouchtool"
cask "chromium"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "franz"
cask "gimp"
cask "google-chrome"
cask "graphiql"
cask "hyperswitch"
cask "insomnia"
cask "intellij-idea"
cask "iterm2"
cask "java"
cask "kap"
cask "keyboard-cleaner"
cask "keycastr"
cask "kindle"
cask "minecraft"
cask "pycharm"
cask "rubymine"
cask "sketch"
cask "skim"
cask "skitch"
cask "skype"
cask "slack"
cask "steam"
cask "teamsql"
cask "vagrant"
cask "visual-studio-code"
cask "webstorm"
cask "xquartz"
mas "", id: 897118787
mas "", id: 497799835
mas "", id: 409183694
mas "", id: 408981434
mas "", id: 693112260
mas "", id: 907364780
mas "", id: 406056744
mas "", id: 1111570163
mas "", id: 549083868
mas "", id: 409201541
mas "", id: 704088911
mas "", id: 539883307
mas "", id: 682658836
mas "", id: 1035516352
mas "", id: 1289197285
mas "", id: 409203825
mas "", id: 409222199
mas "", id: 490461369
